### ISSUE TITLE
Not happy on 3.6.1, 3.5.2

### ISSUE THREAD

**Issue by pathcl** [skyline75489/SimpleDNS#12]
espresso:SimpleDNS pathcl$ sudo simpledns --hosts-file /etc/hosts --upstream-ip 8.8.8.8 -v 2
2017-06-21 13:59:04-0400 [-] Log opened.
2017-06-21 13:59:04-0400 [-] Listening on 127.0.0.1:53
2017-06-21 13:59:04-0400 [-] Using 8.8.8.8:53 as upstream server
2017-06-21 13:59:04-0400 [-] Updating local cache
2017-06-21 13:59:04-0400 [-] DNSDatagramProtocol starting on 53
2017-06-21 13:59:04-0400 [-] Starting protocol <twisted.names.dns.DNSDatagramProtocol object at 0x1042697f0>
2017-06-21 13:59:04-0400 [-] Using Tornado ioloop
2017-06-21 13:59:07-0400 [DNSDatagramProtocol (UDP)] <Query google.cl A IN> query from ('127.0.0.1', 65294)
2017-06-21 13:59:07-0400 [DNSDatagramProtocol (UDP)] Cache miss for b'google.cl'
2017-06-21 13:59:07-0400 [DNSDatagramProtocol (UDP)] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 310, in addCallbacks
	    self._runCallbacks()
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/usr/local/lib/python3.6/site-packages/twisted/names/resolve.py", line 30, in __call__
	    return self.resolver(self.query, self.timeout)
	  File "/usr/local/lib/python3.6/site-packages/twisted/names/common.py", line 73, in query
	    return defer.maybeDeferred(method, query.name.name, timeout)
	--- <exception caught here> ---
	  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 150, in maybeDeferred
	    result = f(*args, **kw)
	  File "/usr/local/lib/python3.6/site-packages/simpledns-0.1.5-py3.6.egg/simpledns/dnsproxy.py", line 245, in lookupAddress

	  File "/usr/local/lib/python3.6/site-packages/simpledns-0.1.5-py3.6.egg/simpledns/dnsproxy.py", line 224, in _matchAddress

	builtins.TypeError: a bytes-like object is required, not 'str'

2017-06-21 13:59:07-0400 [DNSDatagramProtocol (UDP)] Replying with no answers
2017-06-21 13:59:07-0400 [DNSDatagramProtocol (UDP)] Processed query in 0.002 seconds
2017-06-21 13:59:07-0400 [DNSDatagramProtocol (UDP)] Lookup failed
^C2017-06-21 13:59:14-0400 [-] Exiting
espresso:SimpleDNS pathcl$ python3
Python 3.6.1 (default, Apr  4 2017, 09:40:51)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

OS : OSX Capitan

**Comment by pathcl** [comment]
Also it fails on 3.5.2 at least using pip

~ > sudo pip3 install simpledns
[sudo] password for lsanmartin:
The directory '/home/lsanmartin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/lsanmartin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting simpledns
  Downloading simpledns-0.1.4.tar.gz (64kB)
    100% |████████████████████████████████| 71kB 255kB/s
Collecting twisted>=14.0.0 (from simpledns)
  Downloading Twisted-17.5.0.tar.bz2 (3.0MB)
    100% |████████████████████████████████| 3.0MB 444kB/s
Collecting zope.interface>=4.0.2 (from twisted>=14.0.0->simpledns)
  Downloading zope.interface-4.4.2-cp35-cp35m-manylinux1_x86_64.whl (172kB)
    100% |████████████████████████████████| 174kB 3.5MB/s
Collecting constantly>=15.1 (from twisted>=14.0.0->simpledns)
  Downloading constantly-15.1.0-py2.py3-none-any.whl
Collecting incremental>=16.10.1 (from twisted>=14.0.0->simpledns)
  Downloading incremental-17.5.0-py2.py3-none-any.whl
Collecting Automat>=0.3.0 (from twisted>=14.0.0->simpledns)
  Downloading Automat-0.6.0-py2.py3-none-any.whl
Collecting hyperlink>=17.1.1 (from twisted>=14.0.0->simpledns)
  Downloading hyperlink-17.2.1-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python3.5/dist-packages (from zope.interface>=4.0.2->twisted>=14.0.0->simpledns)
Collecting attrs (from Automat>=0.3.0->twisted>=14.0.0->simpledns)
  Downloading attrs-17.2.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in ./.local/lib/python3.5/site-packages (from Automat>=0.3.0->twisted>=14.0.0->simpledns)
Installing collected packages: zope.interface, constantly, incremental, attrs, Automat, hyperlink, twisted, simpledns
  Running setup.py install for twisted ... done
  Running setup.py install for simpledns ... done
Successfully installed Automat-0.6.0 attrs-17.2.0 constantly-15.1.0 hyperlink-17.2.1 incremental-17.5.0 simpledns-0.1.4 twisted-17.5.0 zope.interface-4.4.2
You are using pip version 8.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

Python 3.5.2 (default, Nov 17 2016, 17:05:23)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by skyline75489** [comment]
Do not use pip. It uses py2. Clone this project if you wanna use py3.

**Comment by pathcl** [comment]
Even using your readme it is failing. Its not a matter if I use pip or python setup.py install

**Comment by skyline75489** [comment]
Then maybe there's indeed some problem. I've just recently made it work on Py3. You can revert it to previous commit and use it with Py2.

**Comment by pathcl** [comment]
If I try to run on py2 it says 'You need python 3.4' when executing
simpledns.

I think the issue its related on how simpledns is using twisted, see the
message above.

**Comment by skyline75489** [comment]
Just revert last commit. Luckily it's just one commit.

**Comment by skyline75489** [comment]
Fixed by 0ecc9c854c5fec7a78a3cd7fdf94f6693fa16a52
