### ISSUE TITLE
module 错误 macOS high sierra beta8

### ISSUE THREAD

**Issue by willisworley** [skyline75489/SimpleDNS#15]
>sudo simpledns
Traceback (most recent call last):
  File "/usr/local/bin/simpledns", line 9, in <module>
    load_entry_point('simpledns==0.1.5', 'console_scripts', 'simpledns')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2697, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.macosx-10.13-intel/egg/simpledns/dnsproxy.py", line 51, in <module>
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/internet/default.py", line 50, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/internet/selectreactor.py", line 18, in <module>
    from twisted.internet import posixbase
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/Library/Python/2.7/site-packages/Twisted-17.9.0rc1-py2.7-macosx-10.13-intel.egg/twisted/internet/_sslverify.py", line 38, in <module>
    TLSVersion.TLSv1_1: SSL.OP_NO_TLSv1_1,
AttributeError: 'module' object has no attribute 'OP_NO_TLSv1_1'

**Comment by skyline75489** [comment]
现在只支持 Python 3 了
